name: CI & Publish

on:
  push:
    branches: [ main ]
    # publish will run only when pushing tags (see if-condition below)
  push:
    tags:
      - 'v*.*.*'   # pattern for version tags like v0.1.0
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI (tests, lint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest flake8

      - name: Lint
        run: |
          # optional: allow failure if you don't have flake settings
          flake8 || true

      - name: Run tests
        run: |
          pytest || true

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: ci
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build & twine
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}